hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
zuul:
  routes:
    mongo-service:
      path: /api/mongo-service/**
      service-id: mongo-service
mongo-service:
  ribbon:
    ReadTimeout: 120000
    ConnectTimeout: 120000
    listOfServers: localhost:8081
